// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prueba_2.WebAPInuxiba;

#nullable disable

namespace WebAPInuxiba.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Prueba_2.WebAPInuxiba.Models.Employee", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Sueldo")
                        .HasColumnType("double");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("EmpleadoId");

                    b.HasIndex("userId");

                    b.ToTable("empleados");
                });

            modelBuilder.Entity("Prueba_2.WebAPInuxiba.Models.User", b =>
                {
                    b.Property<int>("userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .HasColumnType("longtext");

                    b.Property<string>("Materno")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("Paterno")
                        .HasColumnType("longtext");

                    b.HasKey("userid");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("Prueba_2.WebAPInuxiba.Models.Employee", b =>
                {
                    b.HasOne("Prueba_2.WebAPInuxiba.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
